version: 2
jobs:
  build:
    working_directory: ~/workspace

    docker:
      - image: circleci/node:7

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Build image
          command: |
            docker build -t app .

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build

